# Generated by Django 3.1.1 on 2020-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('origin', models.CharField(choices=[('GK', 'Greek'), ('JP', 'Japanese'), ('SV', 'Slavic'), ('NR', 'Norse')], max_length=2)),
                ('role', models.CharField(choices=[('GD', 'God'), ('DM', 'Demon'), ('HR', 'Hero'), ('MN', 'Monster')], max_length=2)),
                ('traits', models.CharField(max_length=20)),
                ('greatest_Feats', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
