# Generated by Django 3.1.1 on 2020-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='parents',
            field=models.CharField(default='Cronus and Rhea', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='greatest_Feats',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='traits',
            field=models.CharField(max_length=50),
        ),
    ]
