# Generated by Django 3.1.1 on 2020-09-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20200930_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='traits',
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
