# Generated by Django 3.1.1 on 2020-10-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20200930_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='title',
            field=models.CharField(default='god', max_length=50),
            preserve_default=False,
        ),
    ]
