# Generated by Django 3.1.1 on 2020-10-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_entity_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('origin', 'name')},
        ),
    ]
